CLASS
    EXPRESSION "1"
    LABEL
        FONT [font]
        TYPE TRUETYPE
        COLOR 0 0 0
        SIZE [height]
        POSITION [position]
        ANGLE [orientdeg]
    END
END
CLASS
    EXPRESSION "2"
    LABEL
        FONT [font]
        TYPE TRUETYPE
        COLOR "#0099ff"
        SIZE [height]
        POSITION [position]
        ANGLE [orientdeg]
    END
END
#CLASS
#    EXPRESSION "3"
#    LABEL
#        FONT [font]
#        TYPE TRUETYPE
#        COLOR "#ff0000"
#        SIZE [height]
#        POSITION [position]
#        ANGLE [orientdeg]
#    END
#END
CLASS
    EXPRESSION "4"
    LABEL
        FONT [font]
        TYPE TRUETYPE
        COLOR "#333333"
        SIZE [height]
        POSITION [position]
        ANGLE [orientdeg]
    END
END
#CLASS
#    EXPRESSION "5"
#    LABEL
#        FONT [font]
#        TYPE TRUETYPE
#        COLOR "#ff00ff"
#       SIZE [height]
#        POSITION [position]
#        ANGLE [orientdeg]
#    END
#END
