Pick container: Which container do you need?
Replacement: Why do you need a\nreplacement container?
About you1: Summary\nEND { style.fill: lightgrey }
About you2: Summary\nEND { style.fill: lightgrey }
About you5: Summary\nEND { style.fill: lightgrey }
why_sacks: Why do you need\nmore sacks?
why_green: Why do you need a\nreplacement container?
Call us: Call us\nEND { style.fill: lightgrey }

Pick container -> Call us: Grey bin
Pick container -> why_sacks: Clear sack
Pick container -> why_green: Green bin
Pick container -> Replacement: Other

why_sacks -> About you1: I am a new resident\nwithout any
why_sacks -> About you1: I have used all\nthe sacks provided

why_green -> recent_order: My container\nis damaged
why_green -> recent_order: My container\nis missing

Replacement -> how_long_lived: I am a new resident\nwithout a container
Replacement -> recent_order: My container\nis damaged
Replacement -> recent_order: My container\nis missing
Replacement -> recent_order2: I would like an\nextra container

recent_order: Check if recent order { style.fill: lightblue }
recent_order -> About you2: No recent order
recent_order -> Referral: Recent order

recent_order2: Check if recent order { style.fill: lightblue }
recent_order2 -> About you5: No recent order
recent_order2 -> extra_refusal: Recent order

how_long_lived: How long have you\nlived at this address?
how_long_lived -> recent_order: Less than 3 months
how_long_lived -> Referral2: 3 months or more

extra_refusal: Refuse\nEND { style.fill: lightgrey }

Referral: Summary\nEND\nReferral { style.fill: lightgrey }
Referral2: Summary\nEND\nReferral { style.fill: lightgrey }
