Pick container: Which container do you need?
Replacement: Why do you need a\nreplacement container?
About you1: Summary\nEND { style.fill: lightgrey }
About you2: Summary\nEND { style.fill: lightgrey }
About you5: Summary\nEND { style.fill: lightgrey }
why_sacks: Why do you need\nmore sacks?
why_green: Why do you need a\nreplacement container?
Call us: Call us\nEND { style.fill: lightgrey }

Pick container -> Call us: Grey bin
Pick container -> why_sacks: Clear sack
Pick container -> why_green: Green bin
Pick container -> Replacement: Other

why_sacks -> About you1: I am a new resident\nwithout any
why_sacks -> About you1: I have used all\nthe sacks provided

why_green -> About you2: My container\nis damaged
why_green -> About you2: My container\nis missing

Replacement -> About you5: I am a new resident\nwithout a container
Replacement -> About you5: My container\nis damaged
Replacement -> About you5: My container\nis missing
Replacement -> About you5: I would like an\nextra container
