Pick container: Which container do you need?
Replacement: Why do you need a\nreplacement container?
About you: Summary\nEND { style.fill: lightgrey }

Pick container -> Call us: grey bin
Pick container -> Replacement: blue sack
Pick container -> Replacement: blue bin
Pick container -> Replacement: Food waste caddy

Call us: Call us\nEND { style.fill: lightgrey }


Replacement -> Date_Moved: I am a new resident\nwithout a container
Replacement -> About you: My container\nis damaged
Replacement -> About you: My container\nis missing
Replacement -> About you: I would like an\nextra container

Date_Moved: How long have you lived at this address?
Date_Moved -> About you: < 3 months
Date_Moved -> About you: >= 3 months
