Pick container: Which containers do you need?
Foreach: |latex
    \displaylines{
        \large{\text{For each type of container chosen}} \\
        \text{(and always both types of recycling container)}
    }
|
Foreach.shape: rectangle
Payment\nprovider: { style.fill: lightgreen }
How many: How many people live\nin this household?

Foreach {
    Removal: How many do you wish removing?
    Removal -> Zero
    Removal -> One
    Removal -> '...'
    Removal -> Number\nrequested
}

Pick container -> Foreach: Pick containers/\nquantities
Foreach -> How many: If refuse bin requested,\nnone to be removed
How many -> About you: 1-4\n(180L)
How many -> About you: 5+\n(240L)
Foreach -> About you: Otherwise
About you -> Payment\nprovider: Includes\nchargeable\ncontainers
About you -> END: No\nchargeable\ncontainers

About you: About/\nSummary
Payment\nprovider -> Payment\nconfirmation
Payment\nconfirmation -> END

END { style.fill: lightgrey }


