Pick container: Which container do you need?
Replacement: Why do you need a\nreplacement container?
About you: About/\nSummary/\nEND { style.fill: lightgrey }

Pick container -> Replacement: Other
Pick container -> About you: Recycling blue stripe bag\nor Paper single use bag

Replacement -> About you: Damaged/\nMissing
