name: Deploy D2 documentation to pages

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - name: Install packages
        run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - name: Generate diagrams
        run: |
          for file in diagrams/*.d2; do
            base="${file%.*}"
            ~/.local/bin/d2 $file _site/$base.svg -t 105 --sketch
          done
      - name: Generate index
        run: diagrams/make-index.pl
      - uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
